version: '3'
services:

  #PHP Service
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app_encontrofretes
    restart: unless-stopped
    ports:
      - "1012:80"
      - "1013:443"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      LUMEN_HOST: http://app
    working_dir: /var/www/html
    volumes:
      - ./../:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.inicd
    networks:
      - app-network
    depends_on:
      - db

  #MySQL Service
  db:
    image: mariadb:10.5.11
    container_name: db_encontrofretes
    restart: unless-stopped
    ports:
      - "0005:3306"
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "#tr0caf0ne#"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "#tr0caf0ne#"
      MYSQL_DATABASE: "encontrofretes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-network
  db_sql:
    image: phpmyadmin/phpmyadmin
    ports:
      - "0004:80"
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=1024M
    depends_on:
      - db
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local